# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AlarmClockApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlarmClockApp
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'AlarmClockAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlarmClockAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
